"""Add Event and Trail models

Revision ID: 199acb367744
Revises: 5c9b392b4d9b
Create Date: 2026-01-11 05:30:01.466854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199acb367744'
down_revision = '5c9b392b4d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_event_date'), ['event_date'], unique=False)

    op.create_table('trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Integer(), nullable=True),
    sa.Column('start_point', sa.String(length=200), nullable=True),
    sa.Column('end_point', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('gpx_file', sa.String(length=500), nullable=True),
    sa.Column('water_sources', sa.Boolean(), nullable=True),
    sa.Column('shelters', sa.Boolean(), nullable=True),
    sa.Column('scenic_views', sa.Boolean(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trail_difficulty'), ['difficulty'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trail_difficulty'))

    op.drop_table('trail')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_event_date'))

    op.drop_table('event')
    # ### end Alembic commands ###
