"""add content_block and content_revision tables

Revision ID: 2f943d46195a
Revises: 8814a19e0b02
Create Date: 2026-10-04 06:54:49.748647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f943d46195a'
down_revision = '8814a19e0b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='fk_content_block_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page', 'key', name='uq_content_block_page_key')
    )
    with op.batch_alter_table('content_block', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_block_page'), ['page'], unique=False)

    op.create_table('content_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['content_block.id'], name='fk_content_revision_block_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_content_revision_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_revision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_revision_block_id'), ['block_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_revision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_revision_block_id'))

    op.drop_table('content_revision')
    with op.batch_alter_table('content_block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_block_page'))

    op.drop_table('content_block')
    # ### end Alembic commands ###
