"""Prošireni Post model sa imenovanim foreign key

Revision ID: 652fff0e2552
Revises: 41fd2ba7cd98
Create Date: 2026-01-10 18:37:56.200323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652fff0e2552'
down_revision = '41fd2ba7cd98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('content_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preview', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_post_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_slug'), ['slug'], unique=True)
        batch_op.create_foreign_key('fk_post_author_id', 'user', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_author_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_post_slug'))
        batch_op.drop_index(batch_op.f('ix_post_published'))
        batch_op.drop_index(batch_op.f('ix_post_category'))
        batch_op.drop_column('likes_count')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('author_id')
        batch_op.drop_column('images')
        batch_op.drop_column('image_count')
        batch_op.drop_column('word_count')
        batch_op.drop_column('category')
        batch_op.drop_column('preview')
        batch_op.drop_column('content_text')
        batch_op.drop_column('content_html')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
