"""Add gallery_image table, trail modal columns, fix user.role not null

Revision ID: 8814a19e0b02
Revises: 132238bfd91f
Create Date: 2026-09-22 08:47:46.744790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8814a19e0b02'
down_revision = '132238bfd91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_data', sa.LargeBinary(), nullable=False),
    sa.Column('image_mime', sa.String(length=50), nullable=False),
    sa.Column('image_size', sa.Integer(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('thumbnail_data', sa.LargeBinary(), nullable=True),
    sa.Column('thumbnail_mime', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gallery_image_category', 'gallery_image', ['category'], unique=False)

    op.add_column('trail', sa.Column('features', sa.JSON(), nullable=True))
    op.add_column('trail', sa.Column('equipment', sa.JSON(), nullable=True))
    op.add_column('trail', sa.Column('warning', sa.Text(), nullable=True))
    op.add_column('trail', sa.Column('contact', sa.String(length=100), nullable=True))

    op.alter_column('user', 'role', existing_type=sa.VARCHAR(length=20), nullable=False)
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.drop_index('ix_user_username', table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    op.drop_index('ix_user_username', table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.alter_column('user', 'role', existing_type=sa.VARCHAR(length=20), nullable=True)

    op.drop_column('trail', 'contact')
    op.drop_column('trail', 'warning')
    op.drop_column('trail', 'equipment')
    op.drop_column('trail', 'features')

    op.drop_index('ix_gallery_image_category', table_name='gallery_image')
    op.drop_table('gallery_image')
