"""add gpx columns to trail

Revision ID: bc5c1079df8c
Revises: 1f6b315dabb8
Create Date: 2026-10-06 07:05:29.420115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5c1079df8c'
down_revision = '1f6b315dabb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gpx_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('gpx_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('has_gpx', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.drop_column('has_gpx')
        batch_op.drop_column('gpx_filename')
        batch_op.drop_column('gpx_data')

    # ### end Alembic commands ###
